# Generated by Django 5.1.1 on 2024-09-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_apikey_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=10)),
                ('chats', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='APIkey',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
