# Generated by Django 5.1.1 on 2024-09-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userinfo_delete_apikey_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chats',
            field=models.JSONField(blank=True),
        ),
    ]
