# Generated by Django 5.1.1 on 2024-09-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_userinfo_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
